In [1]:
import os
%pwd

'c:\\Users\\uNUKE\\OneDrive\\Documents\\DSML\\GeoCognition\\prototype'

In [2]:
os.chdir("../")
%pwd

'c:\\Users\\uNUKE\\OneDrive\\Documents\\DSML\\GeoCognition'

In [3]:
import io
import json
from minio import Minio
from dotenv import load_dotenv
import pandas as pd

load_dotenv()

True

# Reading in Data From MinIO

In [25]:
# Connection settings
endpoint = "localhost:9000"  # Update if using a different host/portq
access_key = os.getenv("MINIO_ACCESS_KEY", "minio")
secret_key = os.getenv("MINIO_SECRET_KEY", "minio123")

client = Minio(
    endpoint,
    access_key=access_key,
    secret_key=secret_key,
    secure=False,
)

BUCKET_NAME = "earthquake-curated"
OBJECT_NAME = "year=2026/month=03/day=26/flattened.parquet"

response = client.get_object(BUCKET_NAME, OBJECT_NAME)
try:
    payload = pd.read_parquet(io.BytesIO(response.read()))
finally:
    response.close()
    response.release_conn()

payload

Empty DataFrame
Columns: [type, id, properties.mag, properties.place, properties.time, properties.updated, properties.tz, properties.url, properties.detail, properties.felt, properties.cdi, properties.mmi, properties.alert, properties.status, properties.tsunami, properties.sig, properties.net, properties.code, properties.ids, properties.sources, properties.types, properties.nst, properties.dmin, properties.rms, properties.gap, properties.magType, properties.type, properties.title, longitude, latitude, depth_km]
Index: []

[0 rows x 31 columns]

In [26]:
columns = payload.columns
columns

Index(['type', 'id', 'properties.mag', 'properties.place', 'properties.time',
       'properties.updated', 'properties.tz', 'properties.url',
       'properties.detail', 'properties.felt', 'properties.cdi',
       'properties.mmi', 'properties.alert', 'properties.status',
       'properties.tsunami', 'properties.sig', 'properties.net',
       'properties.code', 'properties.ids', 'properties.sources',
       'properties.types', 'properties.nst', 'properties.dmin',
       'properties.rms', 'properties.gap', 'properties.magType',
       'properties.type', 'properties.title', 'longitude', 'latitude',
       'depth_km'],
      dtype='object')

# Reading from raw JSON

In [10]:
from include.usgs_eq_helper import flatten_eq_json_to_df_helper
from include.constants import EQ_COLUMNS_ORIGINAL

json_path  = "tests/usgs_eq_inputs/healthy_data.json"
json_data = json.load(open(json_path))

df = flatten_eq_json_to_df_helper(json_data, EQ_COLUMNS_ORIGINAL)
# df['properties.type'].unique()

df

,type,id,properties.mag,properties.place,properties.time,properties.updated,properties.tz,properties.url,properties.detail,properties.felt,...,properties.nst,properties.dmin,properties.rms,properties.gap,properties.magType,properties.type,properties.title,longitude,latitude,depth_km
0,Feature,us7000pnd4,4.20,"156 km E of Hicks Bay, New Zealand",1742429566144,1748540194040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,14.0,1.40500,1.11,248.0,mb,earthquake,"M 4.2 - 156 km E of Hicks Bay, New Zealand",-179.925100,-37.587200,10.0000
1,Feature,ak0253mnonmm,2.90,"43 km SSW of Chiniak, Alaska",1742431122091,1748540184040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,NaN,NaN,0.38,NaN,ml,earthquake,"M 2.9 - 43 km SSW of Chiniak, Alaska",-152.467100,57.235300,24.2000
2,Feature,tx2025fmor,3.00,"53 km SSW of Whites City, New Mexico",1742431381802,1748540184040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,29.0,0.00000,0.10,89.0,ml,earthquake,"M 3.0 - 53 km SSW of Whites City, New Mexico",-104.570000,31.726000,6.0999
3,Feature,us7000pnd5,4.10,south of the Fiji Islands,1742431626010,1748540194040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,18.0,6.81800,0.44,183.0,mb,earthquake,M 4.1 - south of the Fiji Islands,179.904800,-24.373500,522.7010
4,Feature,ak0253mo7yuv,2.50,"20 km SSE of Chignik, Alaska",1742434133400,1748540184040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,NaN,NaN,0.42,NaN,ml,earthquake,"M 2.5 - 20 km SSE of Chignik, Alaska",-158.277700,56.120900,67.6000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
147,Feature,pr2025079006,4.05,"143 km NNE of Vieques, Puerto Rico",1742510734100,1748540187040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,21.0,1.32960,0.19,264.0,md,earthquake,"M 4.1 - 143 km NNE of Vieques, Puerto Rico",-65.347000,19.635600,64.0000
148,Feature,us7000plg5,4.50,Mid-Indian Ridge,1742511587669,1748540187040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,35.0,39.41700,0.67,72.0,mb,earthquake,M 4.5 - Mid-Indian Ridge,66.824800,-16.287100,10.0000
149,Feature,us7000plg4,5.00,southeast Indian Ridge,1742512396427,1748540187040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,40.0,17.85800,0.41,54.0,mww,earthquake,M 5.0 - southeast Indian Ridge,102.321900,-46.699100,10.0000
150,Feature,ci40905655,2.53,"10 km ENE of Borrego Springs, CA",1742513388020,1748540187040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,4.0,...,97.0,0.07183,0.19,20.0,ml,earthquake,"M 2.5 - 10 km ENE of Borrego Springs, CA",-116.280333,33.294667,10.4700
151,Feature,us7000pmu1,2.80,"92 km SE of King Cove, Alaska",1742513409244,1748540193040,None,https://earthquake.usgs.gov/earthquakes/eventp...,https://earthquake.usgs.gov/fdsnws/event/1/que...,NaN,...,23.0,0.77100,0.95,225.0,ml,earthquake,"M 2.8 - 92 km SE of King Cove, Alaska",-161.362900,54.437400,35.0000